### ISSUE TITLE
Rebalance incomplete

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [ChrisAdderley/CryoTanks#13]
I see you've updated the tank types and tank switcher patches to have your ZBO tanks weight the same as lifter tanks (0.25 kg per 10 units LH2), but the dry masses of the tanks themselves are still the same values -- so (for example) the HI-M-10 has 3200 units of volume and should weigh 0.8 tons in its LH2 variant (which it does in the B9PartSwitcher module), but its "mass" variable is still 1 ton, so it weighs 0.2 tons too much in all variants.  Likewise for your other LH2 tanks.

I'd make a pull request with the fixes, but I see you haven't committed the rebalanced tank type and tank switcher patches to this repo yet, so I don't want to risk stepping on any files.

**Comment by ChrisAdderley** [comment]
Fixed with your PR being merged.
