### ISSUE TITLE
Omit Wild Blue Resource switcher in switching patch

### ISSUE THREAD

**Issue by ChrisAdderley** [ChrisAdderley/CryoTanks#16]
Simply, add !MODULE[WBIResourceSwitcher to the general patch to stop other mods' fuel switchers being overwritten.

**Comment by jsolson** [comment]
You may want to add !MODULE[ModuleB9PartSwitch] to the list as well. We're protected at the moment by removing the resources when adding the fuel switcher, but there is a [scenario](http://forum.kerbalspaceprogram.com/index.php?/topic/140541-121-b9partswitch-v152-nov-23-switch-fuels-models-nodes-and-more/&do=findComment&comment=2868175) where we would leave them in place. It does appear that B9 ignores the second instance when the module is added twice so this is not urgent.

**Comment by ChrisAdderley** [comment]
Done in next version
