### ISSUE TITLE
Half-spherical stack tanks

### ISSUE THREAD

**Issue by Vladimir-csp** [ChrisAdderley/CryoTanks#2]
This may apply not only to cryo stuff, but half-spherical tanks could serve as handy additional storage and stylish endcaps.

**Comment by ChrisAdderley** [comment]
Any additional tanks for any fuel are out of planning until post-KSP 1.1 (and possibly 1.2) occurs due to reasons.

**Comment by ChrisAdderley** [comment]
Probably determined to be not happening
