### ISSUE TITLE
BUG negative mass caused in a part

### ISSUE THREAD

**Issue by theRagingIrishman** [ChrisAdderley/CryoTanks#25]
It was recently brought to my attention that the CryoTanksFuelTankSwitcher.cfg is causing a negative dry mass in a part from MKS when in Liquid Hydrogen configuration. This causes all sorts of problems and explosions.
Some info on the part in question: in stock, it has a dry mass of .25 tons and holds 315 units of Liquid Fuel and 385 units of Oxidizer

also on the Cryogenic Engines forum page for moar visibility

**Comment by ChrisAdderley** [comment]
Resolved as per forum
