### ISSUE TITLE
KSP.log error, Texture * not found

### ISSUE THREAD

**Issue by blackliner** [ChrisAdderley/CryoTanks#26]
There are ERRors in the KSP Log with CryoTanks, because the *.mu files are mentioning *.tga files that do not exist.

Example: 
KSP.log entry:
[LOG 20:14:26.336] Load(Model): CryoTanks/Parts/HydrogenTanks/hydrogen-10/hydrogen-10-1
[ERR 20:14:26.356] Texture 'CryoTanks/Parts/HydrogenTanks/hydrogen-10/hydrogen-10-n' not found!

hydrogen-10-1.mu file asks for hydrogen-10-n.tga (last line if opened with NP++, after _BurnColor)

**Comment by ChrisAdderley** [comment]
It's resolved with the tank revamp in the next version.
