### ISSUE TITLE
Patch request - H20 to LH2 and Ox for Convert-O-Tron 125 MiniISRU

### ISSUE THREAD

**Issue by GHrynk** [ChrisAdderley/CryoTanks#29]
Requesting a patch for COT-125 MiniISRU that provides H20 conversion to LH2/Ox functionality, similar to current CryoTanks patch for COT-250.

**Comment by ChrisAdderley** [comment]
As far as I'm aware I don't ship such a patch for the large converter... Are you sure that's this mods doing?

**Comment by GHrynk** [comment]
I was just searching through your ISRU patch looking for Water as an input resource while you were responding, to see if I could tweak the ISRU into a MiniISRSU patch myself, and noticed that only Ore is there.  I initially floated this on RoverDude's MKS page on 19 June and forum user Aelfhe1m was kind enough to whip up an edited version of the MKS ISRU H20Splitter patch, but it chokes on CryoTanks unless there's an MKS tank directly in the resource flow path (and before the CryoTank).  I think the missing piece is the flow control language in your CryoTanks patch for ISRU, as the combination of CryoTanks and MKS together appears to enable the COT-250 with H20Splitter to work with your tanks.  With just your tanks and a COT-125 with Aelfhe1m's unofficial H20Splitter patch, it says "Liquid Hydrogen Full" when I activate Water to LH2+Ox, and nothing gets produced.

**Comment by ChrisAdderley** [comment]
You'll have to link me to a copy of that patch. There's nothing functionally different about the two converter patches I have, and the nature of converter modes means that they are fairly orthogonal to each other... Chances are it's something wrong in that patch somehow.

**Comment by GHrynk** [comment]
Here's the link to Aelfhe1m's patch: http://forum.kerbalspaceprogram.com/index.php?/topic/154587-13-modular-kolonization-system-mks/&do=findComment&comment=3097452

My original request is here, as background info: http://forum.kerbalspaceprogram.com/index.php?/topic/154587-13-modular-kolonization-system-mks/&do=findComment&comment=3097439

My next action was going to be submitting an Issue on the MKS GitHub but I'll hold off for now, pending your input.

**Comment by GHrynk** [comment]
On further review of both patches, yours and MKS StockTweaks, it looks like I'm getting ore conversion from your ISRU patch, and just Water from MKS.  The combination of both seems to enable the H20Splitter component to flow Water-->LH2+Ox into CryoTanks for the COT-250.

**Comment by ChrisAdderley** [comment]
That's.... weird. I had a bunch of staring and the MKS patch uses a special converter module - ModuleResourceConverter_USI, which I suspect absolves me of any responsibility here :P. There should be no interaction.

**Comment by GHrynk** [comment]
OK, thanks for checking.  I'll close this out and take it up at MKS again.  If there's anything the COT-250 does that the COT-125 can't (even at reduced efficiency) it would be great to have all the functionality, to enable small, unmanned craft capabilities.
