### ISSUE TITLE
Error spam in log since 0.4.7 update

### ISSUE THREAD

**Issue by tivec** [ChrisAdderley/CryoTanks#39]
```
[EXC 08:47:23.724] InvalidOperationException: Operation is not valid due to the current state of the object
	System.Linq.Enumerable.Single[UrlConfig] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback)
	System.Linq.Enumerable.Single[UrlConfig] (IEnumerable`1 source, System.Func`2 predicate)
	SimpleBoiloff.ModuleCryoTank.Start ()
[EXC 08:47:23.732] NullReferenceException: Object reference not set to an instance of an object
	SimpleBoiloff.ModuleCryoTank.Update ()
[EXC 08:47:23.738] NullReferenceException: Object reference not set to an instance of an object
	SimpleBoiloff.ModuleCryoTank.Update ()
```

Followed by the last error a few thousand times.
[KSP - Cryotanks.zip](https://github.com/ChrisAdderley/CryoTanks/files/1189709/KSP.-.Cryotanks.zip)

**Comment by ChrisAdderley** [comment]
More info. 

When? What part? How do I reproduce it? I follow what appear to be the steps in that log (place a tank in the VAB) with no problems...

**Comment by ChrisAdderley** [comment]
Hang on, that's the stupid part. The one with an `_` in the name that gets replaced with a `.` ingame... I will investigate that angle.

**Comment by tivec** [comment]
I believe it happened when I switched fuel to LH2/Ox in a tank, but I'm not quite sure which tank it was...

**Comment by ChrisAdderley** [comment]
This should be resolved in the last release.

**Comment by tivec** [comment]
I can confirm that the issue no longer shows with the latest version.
Cheers!
