### ISSUE TITLE
3.75 m and 5 m hydrogen tanks have gaps for compact/bare variants

### ISSUE THREAD

**Issue by danfarnsy** [ChrisAdderley/CryoTanks#45]
![image](https://user-images.githubusercontent.com/13547273/34185214-5906b130-e4e1-11e7-9454-853430183ca5.png)

Specifically, the 3.75 m tanks have gaps (as shown) for compact and bare variants. The 5 m tank does not  have a similar gap for compact variant (it lines up just fine), but it does for the bare variant. It looks like a model issue where the inner rings aren't consistently vertically aligned with the outer rings.

**Comment by danfarnsy** [comment]
Update: Bare variant of 2.5 m tank also has a similar gap.

**Comment by ChrisAdderley** [comment]
So are you... sure of this? There are indeed model differences, and when you toggle the tanks to compact and stuff, a different set of attach nodes will be enabled.
For example, from the 2.5m largest tank:
```
node_stack_top01 = 0.0, 3.748542, 0, 0.0, 1.0, 0.0, 2
node_stack_top02 = 0.0, 3.726, 0, 0.0, 1.0, 0.0, 2
```
While `top01` is enabled for the basic variants, `top02` is enabled when the bare variants are selected. This won't be reflected if you toggle them when they are attached because KSP doesn't move parts when the nodes are modified. You would have to reattach them. 

I'll still check it out when I get home today.

**Comment by danfarnsy** [comment]
Regarding the "reattach" test, yes, I detached and reattached parts several times to see how the gaps lined up, checking different parts, etc. In the screenshot above, there is also a gap between the top of the smaller tank and the SpaceY stage separator, immediately prior to which I had removed the assembly of hydrogen tanks and then re-attached it. 

I think I see the issue: In hydrogen-375-1.cfg, for example, the compact variants are using
`			node = top01
			node = bottom01` 

instead of

`			node = top02
			node = bottom02`

Going through and following your suggestion, most of the issues are just a matter of detaching and re-attaching, except for the 3.75 m tank compact variants, for which the gap persists. Bare variants are fine, all 5 m variants are fine, all 2.5 m variants are fine. I'll test that changing that line for the 3.75 m parts fixes the compact variants.

**Comment by danfarnsy** [comment]
Should be resolved with the PR. Two neighboring tanks appear to be fused in a rather nice way, but it doesn't appear to be separate rings welded together as in the full variants. It also means the top ring of the compact variant appears half-embedded in the structure above it. There doesn't appear to be any z-fighting for overlapping placement. Overall, I like the way it looks with this change.

![image](https://user-images.githubusercontent.com/13547273/34246485-110b212a-e5ec-11e7-84ea-ec53c79605e6.png)

vs

![image](https://user-images.githubusercontent.com/13547273/34246495-29ced7c4-e5ec-11e7-837e-374e5c75ab74.png)
