### ISSUE TITLE
Current MM Patch "too aggressive"

### ISSUE THREAD

**Issue by Temeriki** [ChrisAdderley/CryoTanks#51]
I know ckan isnt supported but this isnt a ckan issue.  I installed some other near future mods through ckan, cryo tanks popped up as recommended and I added it as well, its metadata description (I assume set through your git/version files, if not Ill take this to ckan if they fill it out) states "A set of fuel tanks containing liquid hydrogen, with active cryo-cooling."  Making it seem like it was additional hydrogen tanks which is always a win for me.  The only issue I had is the MM patch included overwrites all tanks that can contain lf/ox with your versions.  This superseded IFS and other mods patching CRP fuels in on pretty much every tank in the game (including some other mods tanks designed to work with CRP ).  The specific patch currently included using B9 partswitch to patch into every lf/o tank does make sense in a stock/near future only install, but not when other mods are included that use other fuels.  Maybe make it an optional patch for all lf/o tanks and include only patch near future tanks that can contain cryo fuels(with b9 being used as the texture switcher it makes sense) as standard?

**Comment by ChrisAdderley** [comment]
I think this is actually a bug with the way the MM patch is applied.

Check the contents:
```
@PART[*]:HAS[@RESOURCE[LiquidFuel],@RESOURCE[Oxidizer],!MODULE[InterstellarFuelSwitch],!MODULE[ModuleEnginesFX],!MODULE[ModuleEngines],!MODULE[FSfuelSwitch],!MODULE[WBIConvertibleStorage],!MODULE[WBIResourceSwitcher]]:NEEDS[!modularFuelTanks&!RealFuels]:FOR[zzz_CryoTanks]
```
This should not run if any other fuel switch has already patched the tank. I guess what is probably happening is that all the mods you describe are later in the MM load order, so this patch runs first and then other patches don't. 
I will consult some MM experts to see.

Just to be clear though, your suggestion isn't a great option. This mod relies on a fairly finely configured balance for mass ratios and I know for a fact that IFS and such uses different ratios.
