### ISSUE TITLE
One of the tanks has been losing fuel, but for some reason only one.

### ISSUE THREAD

**Issue by abserver** [ChrisAdderley/CryoTanks#7]
[output_log.txt](https://github.com/ChrisAdderley/CryoTanks/files/276840/output_log.txt)

**Comment by ChrisAdderley** [comment]
This has to do with the old time warp bug. 1000 Ec/s is generated while there is only a capacity for say 2000 Ec/s on the ship. At high timewarp, it's possible for the demand from a single cryo tank to exceed the total remaining Ec on the ship, even through the power source is generating at a higher rate. In this example, at 100,000x timewarp and a physics rate of 0.02, the total draw from a 10Ec/s tank is 10*0.02*100000, or 20,000 Ec/tick. Even through the reactor generates 1000*0.02*100000 (2,000,000) Ec/tick, there  is only 2000 Ec storage on the ship, so the tank fails to cool

This should be resolved in the next release by capping the timewarp scaling of cryo tank draw at 1000x, so it's assumed that if you have the power sources to supply power at 1000x warp, you are fine at all scales.
