### ISSUE TITLE
LMOx tank mass balance point?

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [ChrisAdderley/CryoTanks#85]
Looking at the LMOx tank mass:
https://github.com/ChrisAdderley/CryoTanks/blob/63468f03eda5e23c6368ef1d57f899fcf72bb927/GameData/CryoTanks/Patches/CryoTanksFuelTankTypes.cfg#L112
This tank mass is 1/11th the fuel mass (increased from ~1/14th by commit b451ae9).  If that's intended to represent advanced super-lightweight tank technology, that's great, but the pure LM tank has the usual 1/8th mass figure.  To get the LMOx tank to that balance point, the mass should be 0.000490377.  (Unless I'm using the wrong mass figures or something -- I'm using 0.005 t/unit for Ox, 0.00042561 t/unit for LM).

**Comment by ChrisAdderley** [comment]
Looks like there was a bad cell reference in the spreadsheet I used to derive these, thanks for letting me know.

**Comment by Kerbas-ad-astra** [comment]
Got resolved in 36dec6925cdefbbf23e8f382e71a6d40c4c6c6b5.
