### ISSUE TITLE
Making History: FL-C1000 Fuel tank (Size1p5_Tank_05) tank switcher

### ISSUE THREAD

**Issue by kalmoran** [ChrisAdderley/CryoTanks#95]
ksp version: 1.8.1
CryoTanks version: 1.4

Since the CrytoTanksFuelSwitcher.cfg entires have the 

!MODULE[ModuleEnginesFX],!MODULE[ModuleEngines]

conditions, this fuel tank doesn't have fuel switcher module(due to the SRBs). 
I got a workaround by declaring these switchers for this part as well. But I wonder if there is a better solution:

[CryoTanksFuelTankSwitcherExceptions.txt](https://github.com/ChrisAdderley/CryoTanks/files/4434422/CryoTanksFuelTankSwitcherExceptions.txt)

**Comment by ChrisAdderley** [comment]
I'll think about a cleaner solution. Might be acceptable to do a BEFORE[CT] {renamemodule} then AFTER[CT] {add it back}

**Comment by ChrisAdderley** [comment]
Fixed with 1.5.0+
